app/company/controllers.py
from flask import Blueprint, jsonify, request, render_template, session, redirect, url_for
from werkzeug.datastructures import CombinedMultiDict
from app.commons.modules import company
from app.db import get_mysql_conn
import models as company
from app.commons.modules import company as company_module

from app.commons.modules import student as student_module

api = Blueprint('company', __name__, url_prefix = '/company')


def get_id(email):
    conn = get_mysql_conn()
    cursor = conn.cursor()
    query = 'select c_id from company_details where c_email = "%s" ;' % str(email)
    cursor.execute(query)
    res = cursor.fetchone()[0]
    # print res, '=========='
    conn.close()
    return int(res)


def current_jobs(c_id):
    all_data = company.get_all_company_jobs(c_id)
    return all_data

@api.route('/', methods=['GET'])
def index(err_msg = None, msg = None):
    err_msg = None
    # err_msg = 'invalid email'
    return render_template('company_index.html', err_msg = err_msg, msg = msg)

@api.route('/home', methods=['GET'])
def home():
    print 'company home'
    if 'user_email' not in session:
        return render_template('company_index.html', err_msg='Please login..!')
    err_msg = None
    all_jobs = current_jobs(get_id(session['user_email']))
    print all_jobs, '<<<<<<<<<<<<<<<<<<<<<<<<<<<'
    # err_msg = 'invalid email'
    return render_template('company_home.html', err_msg = err_msg, all_jobs = all_jobs)

# @api.route('/view/profile/<c_id>', methods = ['GET'])
# def view_profile(c_id):
#     details = company.get_details(c_id)
#     return render_template('company_profile.html', details = details)

@api.route('/job/<id>', methods = ['GET'])
def job(id):
    details = company.get_job_details()
    return render_template('job_details.html', details)


@api.route('/login', methods = ['GET', 'POST'])
def login():
    print '________________________________________', request.method
    print '______', request.form
    print session
    err_msg = None
    
    if 'user_email' not in session:
        if request.method == 'GET':
            return render_template('company_index.html')
        elif request.method == 'POST':
            # popular_data = student.get_popular_data()
            # recent_jobs = student.get_recent_jobs()
            user_email = request.form['user_email']
            password = request.form['password']
            # check for valid credentials
            valid_user = True
            # print student.exists(user_email), '>>>>>>>>>>>'
            # print '###########', student.correct_credentials(user_email, password)

            # print student.exists(user_email), '___user exists'
            # print student.correct_credentials(user_email, password), 'correct pwd'
            if company.exists(user_email) and company_module.correct_credentials(user_email, password):
                # print '################'
                session['user_email'] = user_email
                print 'logged in ..................................................'
                # print '_________user inserted ', session
                # print '++++++++++++ ', recent_jobs
                # return redirect(url_for(company.home))
                # return render_template('company_home.html', user_email = user_email, popular_data = popular_data, recent_jobs = recent_jobs)
                err_msg = None
                all_jobs = current_jobs(get_id(session['user_email']))
                print all_jobs, '<<<<<<<<<<<<<<<<<<<<<<<<<<<'
                # err_msg = 'invalid email'
                return render_template('company_home.html', err_msg = err_msg, all_jobs = all_jobs)
            else:
                return render_template('company_home.html', err_msg = 'invalid credentials')
    else:
        # popular_data = student.get_popular_data()
        # recent_jobs = student.get_recent_jobs()
        return render_template('company_home.html', err_msg = err_msg)

    print '________________________________________', request.method
    print '______', request.form
    print session
    if 'user_email' not in session:
        if request.method == 'GET':
            return render_template('company_index.html')
        elif request.method == 'POST':
            user_email = request.form['user_email']
            password = request.form['password']
            # check for valid credentials
            valid_user = True
            print company.exists(user_email), '>>>>>>>>>>>'
            print '###########', company_module.correct_credentials(user_email, password)
            try:
                if company.exists(user_email) and company_module.correct_credentials(user_email, password):
                    print '################'
                    session['user_email'] = user_email
                    print '_________user inserted ', session
                    return render_template('company_home.html', user_email = user_email)
                else:
                    return render_template('company_index.html', err_msg= 'User not found, or Invalid credentials!')
            except Exception, e:
                return render_template('company_index.html', err_msg= 'Oops..Something went wrong!')
    else:
        return render_template('company_home.html', user_email = session['user_email'])

@api.route('/logout', methods= ['GET'])
def logout():
    session.pop('user_email', None)
    print session
    return redirect(url_for('company.index'))
    return render_template('company_index.html', msg = 'Logout Successful.!')

@api.route('/test', methods=['GET'])
def test():
    print session
    return 'test from controller - company'

@api.route('/register', methods = ['POST'])
def register():
    response = company.register(request.form)
    if company.exists(str(request.form['user_email'])):
        return render_template('company_index.html', err_msg = 'Account already created! ')

    if response['status'] == 'success':
        return render_template('company_index.html', msg = 'Success.! Please login now.!')
    else:
        print '_________ERROR:', response['message']
        return render_template('company_index.html', err_msg = 'Error.! Please try later. ')


@api.route('/student_view', methods = ['GET'])
def view_student():

    data = student_module.get_student_profile(int(request.args['st_id']))
    return render_template('company_view_student.html', data = data['data'])

@api.route('/job', methods = ['GET'])
def job_details_fn():
    data = company.get_job(int(request.args['job_id']))
    print data
    return render_template('job_view_company.html', data=data[0])


@api.route('/applications', methods = ['GET'])
def applications():
    all_data = []

    conn = get_mysql_conn()
    cursor = conn.cursor()
    query = 'select st_id,st_name, job_id,job_title,  c_id, st_university, st_major from job_applications natural join company_details natural join student_profile natural join job_announcements  where c_id = %d;' % int(get_id(str(session['user_email'])))
    cursor.execute(query)
    res = cursor.fetchall()

    for r in res:
        data = {}
        data['st_id'] = r[0]
        data['st_name'] = r[1]
        data['job_id'] = r[2]
        data['job_title'] = r[3]
        data['st_university'] = r[4]
        data['st_major'] = r[5]
        # data[''] = r[]
        all_data.append(data)

    return render_template('applications.html', data = all_data)
   

app/student/controllers.py
from flask import Blueprint, jsonify, request, render_template, session, redirect, url_for
from werkzeug.datastructures import CombinedMultiDict
from app.commons.modules import student 
from app.db import get_mysql_conn
import datetime
import time
import models as student_model



api = Blueprint('student', __name__, url_prefix = '/student')

# @api.before_request
# def before_request():
#     # if 'logged_in' not in session and request.endpoint != 'student.login':
#     if 'logged_in' not in session:
#         print session
#         print request.endpoint
#         print '@@@@@@@@@@@ through before request'
#         return render_template('student_login.html')
# @api.route('/shradha', methods=['GET'])
# def shradha():
#     return render_template('test.html')

@api.route('/', methods=['GET'])
def index(err_msg = None, msg = None):
    err_msg = None
    # err_msg = 'invalid email'
    return render_template('student_index.html', err_msg = err_msg, msg = msg)

@api.route('/home', methods=['GET'])
def home_page():
    # print 'student home'
    if 'user_email' not in session:
        return render_template('student_index.html', err_msg='Please login..!')
    err_msg = None
    popular_data = student.get_popular_data()
    recent_jobs = student.get_recent_jobs()
    # print popular_data, '$$$$$$$$$$$$$$$'
    # err_msg = 'invalid email'
    all_data = all_notifications(int(student.get_id(session['user_email'])))
    return render_template('student_home.html', err_msg = err_msg, popular_data = popular_data, recent_jobs = recent_jobs, all_data = all_data)



@api.route('/job_search', methods = ['GET', 'POST'])
def job_search():
    all_jobs = student.get_all_jobs()
    if request.method == 'POST':
        print request.form['keyword'], '__________________________'
        all_jobs = student.get_all_jobs(keyword = request.form['keyword'])
        print '____________resulttttt', all_jobs
    return render_template('student_job_search.html', all_jobs = all_jobs['data'])


@api.route('/job_view', methods = ['GET'])
def job_view():
    job_id = request.args['job_id']
    data = student.get_job(job_id)
    st_id = student.get_id(session['user_email'])

    conn = get_mysql_conn()
    cursor = conn.cursor()
    print '__________previous insert'

    query = 'select * from job_applications where st_id = %d and job_id = %d' % (int(st_id), int(job_id))
    print query

    cursor.execute(query)
    if cursor.fetchone() is not None:
        print '+++++++++ already applied.. '
        conn.close()
        return render_template('job_announcement_view.html', data = data['data'][0], user_email = session['user_email'], job_id = job_id, applied = True)


    
    return render_template('job_announcement_view.html', data = data['data'][0], user_email = session['user_email'], job_id = job_id)



@api.route('/profile_edit', methods = ['GET', 'POST'])
def profile_edit():
    s_id = student.get_id(session['user_email'])
    if request.method == 'GET':
        data = student.get_student_profile(int(s_id))
        print data['data']
        return render_template('student_profile_edit.html', data = data['data'])
    else:
        resume = None
        # print '__________________PIOST aa gyaaa'
        print request.form, 'in the form'
        if request.files:
            resume = request.files['st_resume']
        # print resume, '<<<<<<<<<<<<<<'
        # resume_data = 
        # update db
        print 'before update'
        update_status = student.update_student_profile(int(s_id), resume = resume, data = request.form)
        print 'after calling update'
        data = student.get_student_profile(int(s_id))
        return render_template('student_profile_edit.html', msg = 'Updated.!', data = data['data'])


@api.route('/follow_company', methods = ['GET'])
def follow_company():
    # return request.args['c_id']
    print 'in controller'
    c_id = int(request.args['c_id'])
    st_id = student.get_id(session['user_email'])
    data = student.company_profile(int(c_id))
    recent_jobs = student.get_company_jobs(int(c_id))
    student.follow_company(c_id, st_id)
    allow_follow = True

    print 'after in controller'
    following = student.is_following_company(int(c_id), int(st_id))
    if following:
        allow_follow = False    
    return render_template('company_profile.html', data = data['data'], recent_jobs = recent_jobs, allow_follow = allow_follow, c_id = c_id)


@api.route('/view_company', methods = ['GET'])
def view_company():
    c_id = request.args['c_id']
    # c_id = 2
    data = student.company_profile(int(c_id))
    recent_jobs = student.get_company_jobs(int(c_id))
    st_id = student.get_id(session['user_email'])
    print st_id
    allow_follow = True

    print 'after in controller'
    following = student.is_following_company(int(c_id), int(st_id))
    if following:
        allow_follow = False    
    return render_template('company_profile.html', data = data['data'], recent_jobs = recent_jobs, allow_follow = allow_follow, c_id = c_id)


@api.route('/login', methods = ['GET', 'POST'])
def login():
    print '________________________________________', request.method
    print '______', request.form
    print session

    if 'user_email' not in session:
        if request.method == 'GET':
            return render_template('student_index.html')
        elif request.method == 'POST':
            popular_data = student.get_popular_data()
            recent_jobs = student.get_recent_jobs()
            user_email = request.form['user_email']
            password = request.form['password']
            # check for valid credentials
            valid_user = True
            # print student.exists(user_email), '>>>>>>>>>>>'
            # print '###########', student.correct_credentials(user_email, password)

            print student.exists(user_email), '___user exists============='
            print student.correct_credentials(user_email, password), 'correct pwd'
            if not student.exists(user_email):
                return render_template('student_index.html', err_msg= 'User not found, or Invalid credentials!')

            if student.exists(user_email) and student.correct_credentials(user_email, password):
                # print '################'
                session['user_email'] = user_email
                # print '_________user inserted ', session
                print '++++++++++++ ', recent_jobs
                all_data = all_notifications(int(student.get_id(session['user_email'])))
                return render_template('student_home.html', user_email = user_email, popular_data = popular_data, recent_jobs = recent_jobs, all_data = all_data)
            else:
                print '&&&&&&&&&&&&&&&&&&&&'
                return render_template('student_index.html', err_msg= 'User not found, or Invalid credentials!')
    else:
        popular_data = student.get_popular_data()
        recent_jobs = student.get_recent_jobs()
        return render_template('student_home.html', user_email = session['user_email'], popular_data = popular_data, recent_jobs = recent_jobs)

@api.route('/logout', methods= ['GET'])
def logout():
    session.pop('user_email', None)
    # print session
    return redirect(url_for('student.index'))
    # return render_template('student_index.html', msg = 'Logout Successful.!')

@api.route('/test', methods=['GET'])
def test():
    err_msg = None
    popular_data = student.get_popular_data()
    recent_jobs = student.get_recent_jobs()
    # print popular_data, '$$$$$$$$$$$$$$$'
    # err_msg = 'invalid email'
    return render_template('student_home.html', err_msg = err_msg, popular_data = popular_data, recent_jobs = recent_jobs)

    print session
    return 'test from controller - student'

@api.route('/register', methods = ['POST'])
def register():
    response = student.register(request.form)
    print response, '++++++++++++++++++++'
    # if student.exists(str(request.form['user_email'])):
    #     return render_template('student_index.html', err_msg = 'Email already used.! ')
    if response['status'] == 'success':
        return render_template('student_index.html', msg = 'Success.! Please login now.!')
    else:
        return render_template('student_index.html', err_msg = 'Error.! Please try later. ')





## TODO : correct these functions - currently directly contacting the model, should go via modules

@api.route('/apply_job', methods = ['GET', 'POST'])
def apply_job():
    job_id = int(request.args['job_id'])
    st_id = student.get_id(session['user_email'])
    applied_at = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    applied = False

    # if request.method == 'GET':
    
    print '___________________________________________', request.method
    data = student.get_job(job_id)
    print data
    conn = get_mysql_conn()
    cursor = conn.cursor()
    print '__________previous insert'

    query = 'select * from job_applications where st_id = %d and job_id = %d' % (int(st_id), int(job_id))
    print query

    cursor.execute(query)
    if cursor.fetchone() is not None:
        print '+++++++++ already applied.. '
        conn.close()
        return render_template('job_announcement_view.html', data = data['data'][0], user_email = session['user_email'], job_id = job_id, applied = True)


    # else:
    conn = get_mysql_conn()
    cursor = conn.cursor()
    print '__________previous insert'

    query = 'Insert into job_applications (st_id, job_id, applied_at) values (%d,%d, "%s");' % (int(st_id), int(job_id), applied_at)
    print query
    
    try:
        cursor.execute(query)
        conn.commit()
        print '___________after insert'
        conn.close()
        print 'conn closed'
        data = student.get_job(job_id)
        print data
        applied = True
        return render_template('job_announcement_view.html', data = data['data'][0], user_email = session['user_email'], job_id = job_id, applied = applied)

    except Exception, e:

app/templates/company_index.html
		{% extends "header.html" %}
		{% block body %}
		<body>

		<section id="main" class="wrapper">
						<div class="container">

							<header class="major">
								<h2 align="center"><i class="icon  fa-graduation-cap" style="color: #42b972"></i>    Company Account</h2>
								{% if err_msg %}
								<h3 style="color: red">{{err_msg}}</h3>
								{% endif %}
								{% if msg %}
								<h3 style="color: green">{{msg}}</h3>
								{% endif %}
								<!-- <p>Lorem ipsum dolor sit amet nullam id egestas urna aliquam</p> -->
							</header>

						</div>
		</section>					
					<section id="one" class="wrapper style1 align-center">
						<div class="container">


						<!-- login -->
							<div class="row 200%">
                                <section class="6u 12u$(small)">
                                    <header><h2><span><i class="icon rounded fa-sign-in fa-lg"></i></span>Login to your account</h2></header>
                                    <form method="post" action="{{ url_for('company.login') }}">
                                        <div class="uniform" align="center">
                                            <div class="6u$ 12u$(xsmall)">
                                                <input  type="email" name="user_email" id="user_email" value="" placeholder="Company Email" style="background-color:  #ffffff;color: #000; margin-bottom: 15px" required/>
                                            </div>
                                            <div class="6u$ 12u$(xsmall)">
                                                <input type="password" name="password" id="password" value="" placeholder="Password" style="background-color:  #ffffff;color: #000; margin-bottom: 15px" required />
                                            </div>
                                            <div>
                                            	<input type="submit" value="Login" class="button  big" style="color:black"></input>
                                            <!-- <a href="home" class="button green-bg big "  style="background-color:  #ffffff"> <span style="color: #42b972">Login</span></a> -->
                                            </div>
                                        </div>
                                    </form>
                                </section>




						<!-- register -->
								<section class="6u 12u$(small)">
									<!-- <i class="icon big rounded fa fa-id-card"></i> -->
									<!-- <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium ullam consequatur repellat debitis maxime molestiae.</p> -->
									<header><h2><span><i class="icon rounded fa-id-card fa-lg"></i></span>Create an account </h2></header>
									<form method="post" action="{{ url_for('company.register') }}">
                                        <div class="uniform" align="center">
                                            <div class="6u$ 12u$(xsmall)">
                                                <input type="text" name="user_name" id="user_name" value="" placeholder="Company Name" style="background-color:  #ffffff;color: #000; margin-bottom: 15px" required />
                                            </div>
                                            <div class="6u$ 12u$(xsmall)">
                                                <input  type="email" name="user_email" id="user_email" value="" placeholder="Email" style="background-color:  #ffffff;color: #000; margin-bottom: 15px" required/>
                                            </div>
                                            <div class="6u$ 12u$(xsmall)">
                                                <input type="password" name="password" id="password" value="" placeholder="Password" style="background-color:  #ffffff;color: #000; margin-bottom: 15px" required />
                                            </div>
                                            <div>
                                            	<input type="submit" value="Regsiter" class="button  big" style="color:black"></input>
                                            <!-- <a href="home" class="button green-bg big "  style="background-color:  #ffffff"> <span style="color: #42b972">Login</span></a> -->
                                            </div>
                                        </div>
                                    </form>
								</section>
								<!-- <section class="4u$ 12u$(small)">
									<i class="icon big rounded fa-user"></i>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque eaque eveniet, nesciunt molestias. Ipsam, voluptate vero.</p>
								</section> -->
							</div>
						</div>
					</section>




		{% include 'footer.html' %}
		</body>
		{% endblock %}

app/templates/company_view_student.html
        {% extends "company_home_base.html" %}
        {% block body %}

        <div class="col-12">
            <div class="col-12">
            <!-- {{data}} {{c_id}} -->
            <br>
            <div class="col-6">
              <h5 class="mb-0"><span>Student Details.. </span></h5> <br>
<!-- {{status}} -->
            </div>
           
            </div> 

                    <div class="card">
                      <div class="card-header">
                        <strong>{{data['st_name']}}</strong> 

                      </div>
                      <!-- {{data}} -->
                      <div class="card-body card-block">
                            <!-- <form action="{{ url_for('student.job_search') }}" method="post" enctype="multipart/form-data" class="form-horizontal"> -->
                            {% for key, value in data.iteritems() %}

                            {% if key != 'c_id' and key != 'job_id' %}
                            <div class="row form-group">
                            <div class="col col-md-3"><label class=" form-control-label">{{key}}</label></div>
                            <div class="col-12 col-md-9">
                              <p class="form-control-static">{{value}}</p>
                            </div>
                          </div>
                          {% endif %}

                            {% endfor %}

                            <!-- <div class="row form-group">
                                <div class="col"><label for="email-input" class=" form-control-label">Keyword</label></div>
                                <div class="col-12"><input type="text" id="degree_type" name="keyword"class="form-control"><small class="help-block form-text"></small></div>
                            </div> -->
                            <!-- <button type="submit" class="btn btn-primary btn-sm">
                              <i class="fa fa-dot-circle-o"></i> Search
                            </button> -->
                                <!-- <form action="{{ url_for('student.job_search') }}" method="get" enctype="multipart/form-data" class="form-horizontal"><button type="submit" class="btn btn-primary btn-sm">
                                  <i class="fa fa-dot-circle-o"></i> Reset
                                </button>
                                </form> -->
                            <!-- </form> -->                            
                      </div>
                    </div>
                  
                  </div>
          </div>


        {% endblock %}

app/templates/job_announcement_view.html
                          {% extends "student_home_base.html" %}
        {% block body %}

        <div class="col-12">
			<div class="col-12">
                    <div class="card">
                      <div class="card-header">
                        <strong>Job </strong> Announcement 

                        {% if not applied %}
           <!-- <div class="col-6"> -->
           
             <button type="button" class="btn btn-primary btn-sm"> <a href="/student/apply_job?job_id={{job_id}}" style="color: white"><span><i class="fa fa-star"></i>&nbsp; Apply</span></a></button>  
             <!-- </div>          -->
           {% endif %}
           {% if applied %}

             <button type="button" class="btn btn-success btn-sm"> <i class="fa fa-star"></i>&nbsp; Applied</span></button>
           {% endif %}

                      </div>
                      <div class="card-body card-block">
	                        <!-- <form action="{{ url_for('student.job_search') }}" method="post" enctype="multipart/form-data" class="form-horizontal"> -->
	                        {% for key, value in data.iteritems() %}

	                        {% if key != 'c_id' and key != 'job_id' %}
	                        <div class="row form-group">
                            <div class="col col-md-3"><label class=" form-control-label">{{key}}</label></div>
                            <div class="col-12 col-md-9">
                              <p class="form-control-static">{{value}}</p>
                            </div>
                          </div>
                          {% endif %}

	                        {% endfor %}

	                   		<!-- <div class="row form-group">
	                            <div class="col"><label for="email-input" class=" form-control-label">Keyword</label></div>
	                            <div class="col-12"><input type="text" id="degree_type" name="keyword"class="form-control"><small class="help-block form-text"></small></div>
	                        </div> -->
	                        <!-- <button type="submit" class="btn btn-primary btn-sm">
	                          <i class="fa fa-dot-circle-o"></i> Search
	                        </button> -->
		                        <!-- <form action="{{ url_for('student.job_search') }}" method="get" enctype="multipart/form-data" class="form-horizontal"><button type="submit" class="btn btn-primary btn-sm">
		                          <i class="fa fa-dot-circle-o"></i> Reset
		                        </button>
		                        </form> -->
	                        <!-- </form> -->
	                        
	                        
                      </div>
                      
                     
                    </div>
                  
                  </div>
		  </div>


        {% endblock %}

app/templates/job_notifications.html
        {% extends "student_home_base.html" %}
        {% block body %}
        <body>


		<div class="col-12">
			<br>
			<h5 class="mb-0"><span>Job Notification</span></h5>
			<br>





            



            <!-- {{data}} -->

			{% for job in job_notifications %}
            <div class="col-md-3">
                <div class="card">
                    <div class="card-header"> 
                        <i class="fa fa-building" style="color: #d6319f;"></i><strong class="card-title pl-2"><a href="/student/view_company?c_id={{job['c_id']}}">{{job['c_name']}}</a></strong>
                    </div>
                    <div class="card-body">
                        <div class="mx-auto d-block">
                            <h5 class="text-sm-center mt-2 mb-1"><a href="/student/job_view?job_id={{job['job_id']}}">{{  job['job_title'] | safe}}</a></h5>
                            <div class="location text-sm-center"><i class="fa fa-map-marker"></i> {{job['job_city']}}, {{job['job_state']}}</div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}


		</div>


        </body>
        {% endblock %}

app/templates/student_job_search.html
		{% extends "student_home_base.html" %}
        {% block body %}

<!-- {{all_jobs}} -->

        <body>
        <div class="col-12">
			<div class="col-12">
                    <div class="card">
                      <div class="card-header">
                        <strong>Search </strong> Jobs
                      </div>
                      <div class="card-body card-block">
	                        <form action="{{ url_for('student.job_search') }}" method="post" enctype="multipart/form-data" class="form-horizontal">

	                   		<div class="row form-group">
	                            <div class="col"><label for="email-input" class=" form-control-label">Keyword</label></div>
	                            <div class="col-12"><input type="text" id="degree_type" name="keyword"class="form-control"><small class="help-block form-text"></small></div>
	                        </div>
	                        <button type="submit" class="btn btn-primary btn-sm">
	                          <i class="fa fa-dot-circle-o"></i> Search
	                        </button>
		                        <form action="{{ url_for('student.job_search') }}" method="get" enctype="multipart/form-data" class="form-horizontal"><button type="submit" class="btn btn-primary btn-sm">
		                          <i class="fa fa-dot-circle-o"></i> Reset
		                        </button>
		                        </form>
	                        </form>
	                        
	                        
                      </div>
                      
                     
                    </div>
                  
                  </div>
		  </div>

		<div class="col-12">
			<br>
			<h5 class="mb-0"><span>Recent Job Postings</span></h5>
			<br>
			{% for job in all_jobs %}
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header"> 
                        <i class="fa fa-building" style="color: #d6319f;"></i><strong class="card-title pl-2"><a href="/student/view_company?c_id={{job['c_id']}}">{{job['c_name']}}</a></strong>
                    </div>
                    <div class="card-body">
                        <div class="mx-auto d-block">
                            <h5 class="text-sm-center mt-2 mb-1"><a href="job_view?job_id={{job['job_id']}}">{{  job['job_title'] | safe}}</a></h5>
                            <div class="location text-sm-center"><i class="fa fa-map-marker"></i> {{job['job_city']}}, {{job['job_state']}}</div>
                            <div class="location text-sm-center"><i class="fa fa-calendar"></i> Posted on {{job['posted_date']}}</div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}


		</div>

	
        {% endblock %}